// File generated by FlutterFire CLI
// ignore_for_file: sort_constructors_first
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  /// Default [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyBYGjzXtsWGa0Yw98oF2NfjKxNRt8PQX_s',
        appId: '1:768011264762:web:848f3286bfc552d2975f43',
        messagingSenderId: '768011264762',
        projectId: 'thuma-mina-pay',
        authDomain: 'thuma-mina-pay.firebaseapp.com',
        storageBucket: 'thuma-mina-pay.firebasestorage.app',
        measurementId: 'G-XXXXXXXXXX',
      );
    }
    return const FirebaseOptions(
      apiKey: 'AIzaSyBYGjzXtsWGa0Yw98oF2NfjKxNRt8PQX_s',
      appId: '1:768011264762:android:848f3286bfc552d2975f43',
      messagingSenderId: '768011264762',
      projectId: 'thuma-mina-pay',
      authDomain: 'thuma-mina-pay.firebaseapp.com',
      storageBucket: 'thuma-mina-pay.firebasestorage.app',
    );
  }
}
